/*
 JSG.SVG - JSG SVG Library
 Version_Copyright Tensegrity Software GmbH. Use and distribution currently only with the consent of Tensegrity Software GmbH! Please read and
 follow the license agreement provided with this distribution. If there are any questions regarding the software license, please contact us.
*/
JSG.namespace("JSG.SVG");
JSG.SVG=function(){var c=function(b,a){var e=new XMLHttpRequest;e.open("GET",b,!0);e.overrideMimeType("text/xml");e.onreadystatechange=function(){4===e.readyState&&a&&a(e)};return e},a=function(b){var a;200===b.status&&(a=b.responseXML||b.responseText);if(!a)throw JSG.SVG.Error.createError("Failed to load svg.","Response is undefined!");return a};return{mixin:function(b){var a=arguments,e,f,c,g=a.length;for(c=1;c<g;c++)for(e in f=a[c],f)b[e]=f[e];return b},merge:function(b,a,e){a=a||{};e=!0===e;for(var f in b)!b.hasOwnProperty(f)||
a.hasOwnProperty(f)&&!e||(a[f]=b[f]);return a},load:function(b,d){c(b,function(e){if(d)try{var f=JSG.SVG.fromXML(a(e));f.url=b;d(f)}catch(c){c.url=b,d(void 0,c)}}).send()},fromXML:function(b){var a=b;if("string"===typeof b||b instanceof String)a=(new DOMParser).parseFromString(b,"text/xml");return this.fromDoc(a)},fromDoc:function(b){if(b&&b instanceof XMLDocument){if(JSG.SVG.Error.hasError(b))throw JSG.SVG.Error.createErrorFromDoc(b);b=JSG.SVG.Shapes.createElement(b.documentElement);b.convertValues();
return new JSG.SVG.Model(b)}}}}();JSG.SVG.Model=function(c){this.svg=c;this.url=void 0;this.includeRoot=!0};JSG.SVG.Model.prototype.toJSG=function(c){var a=[];this.svg&&(c=this.svg.toJSG(c),this.includeRoot?a.push(c):a=this._decompose(c));return a};JSG.SVG.Model.prototype._decompose=function(c){var a=[],b=JSG.ptCache.get(),d=c.getAngle().getValue();c.getItems().forEach(function(e){e.getOrigin(b);c.translateToParent(b);e.rotate(d);e.setOriginTo(b);a.push(e)});JSG.ptCache.release(b);return a};JSG.namespace("JSG.SVG");
JSG.SVG.Error=function(){var c=function(a,b){"#text"===b.nodeName.toLowerCase()&&a.messages.push(b.nodeValue);if(b.hasChildNodes()){var d,e,f=b.childNodes;d=0;for(e=f.length;d<e;d++)c(a,f[d])}};return{hasError:function(a){var b=a.documentElement.firstElementChild.nodeName;return"parsererror"===a.documentElement.nodeName.toLowerCase()||"parsererror"===b.toLowerCase()},createErrorFromDoc:function(a){var b={messages:[],toString:function(){return this.messages.join("\n")}};c(b,a.documentElement);return b},
createError:function(a){return{messages:[].slice.call(arguments),toString:function(){return this.messages.join("\n")}}}}}();JSG.namespace("JSG.SVG");
JSG.SVG.Circle=function(){var c={toJSG:function(a){var b=new JSG.graph.model.Node(new JSG.graph.model.shapes.EllipseShape);b.evaluate();var d=JSG.ptCache.get(),e=this.getTransformMatrix(),e=JSG.geometry.Utils.toRadians(e.getRotation());d.x=2*a.deviceToLogX(this.attribute("r",0));d.y=d.x;b.setSizeToPoint(d);d.x=a.deviceToLogX(this.attribute("cx",0));d.y=a.deviceToLogY(this.attribute("cy",0));b.setPinPointTo(d);b.rotate(e);JSG.ptCache.release(d);JSG.SVG.Styles.apply(this,b,a);return b},convert:function(){var a=
this.getTransformMatrix(),b=this.attribute("r",0),d=this.attribute("cx",0),e=this.attribute("cy",0),b=JSG.SVG.Unit.toPixels(b,0,this);a.applyToPoint(b);this.attributes.r=b.x;b=JSG.SVG.Unit.toPixels(d,e,this);b=a.applyToPoint(b);this.attributes.cx=b.x;this.attributes.cy=b.y}};return{createFrom:function(a){a=JSG.SVG.Element.fromNode(a);return JSG.SVG.mixin(a,c)}}}();JSG.namespace("JSG.SVG");
JSG.SVG.Color=function(){var c={aliceblue:"#F0F8FF",antiquewhite:"#FAEBD7",aqua:"#00FFFF",aquamarine:"#7FFFD4",azure:"#F0FFFF",beige:"#F5F5DC",bisque:"#FFE4C4",black:"#000000",blanchedalmond:"#FFEBCD",blue:"#0000FF",blueviolet:"#8A2BE2",brown:"#A52A2A",burlywood:"#DEB887",cadetblue:"#5F9EA0",chartreuse:"#7FFF00",chocolate:"#D2691E",coral:"#FF7F50",cornflowerblue:"#6495ED",cornsilk:"#FFF8DC",crimson:"#DC143C",cyan:"#00FFFF",darkblue:"#00008B",darkcyan:"#008B8B",darkgoldenrod:"#B8860B",darkgray:"#A9A9A9",
darkgreen:"#006400",darkkhaki:"#BDB76B",darkmagenta:"#8B008B",darkolivegreen:"#556B2F",darkorange:"#FF8C00",darkorchid:"#9932CC",darkred:"#8B0000",darksalmon:"#E9967A",darkseagreen:"#8FBC8F",darkslateblue:"#483D8B",darkslategray:"#2F4F4F",darkturquoise:"#00CED1",darkviolet:"#9400D3",deeppink:"#FF1493",deepskyblue:"#00BFFF",dimgray:"#696969",dodgerblue:"#1E90FF",firebrick:"#B22222",floralwhite:"#FFFAF0",forestgreen:"#228B22",fuchsia:"#FF00FF",gainsboro:"#DCDCDC",ghostwhite:"#F8F8FF",gold:"#FFD700",
goldenrod:"#DAA520",gray:"#808080",green:"#008000",greenyellow:"#ADFF2F",honeydew:"#F0FFF0",hotpink:"#FF69B4",indianred:"#CD5C5C",indigo:"#4B0082",ivory:"#FFFFF0",khaki:"#F0E68C",lavender:"#E6E6FA",lavenderblush:"#FFF0F5",lawngreen:"#7CFC00",lemonchiffon:"#FFFACD",lightblue:"#ADD8E6",lightcoral:"#F08080",lightcyan:"#E0FFFF",lightgoldenrodyellow:"#FAFAD2",lightgray:"#D3D3D3",lightgreen:"#90EE90",lightpink:"#FFB6C1",lightsalmon:"#FFA07A",lightseagreen:"#20B2AA",lightskyblue:"#87CEFA",lightslategray:"#778899",
lightsteelblue:"#B0C4DE",lightyellow:"#FFFFE0",lime:"#00FF00",limegreen:"#32CD32",linen:"#FAF0E6",magenta:"#FF00FF",maroon:"#800000",mediumaquamarine:"#66CDAA",mediumblue:"#0000CD",mediumorchid:"#BA55D3",mediumpurple:"#9370DB",mediumseagreen:"#3CB371",mediumslateblue:"#7B68EE",mediumspringgreen:"#00FA9A",mediumturquoise:"#48D1CC",mediumvioletred:"#C71585",midnightblue:"#191970",mintcream:"#F5FFFA",mistyrose:"#FFE4E1",moccasin:"#FFE4B5",navajowhite:"#FFDEAD",navy:"#000080",oldlace:"#FDF5E6",olive:"#808000",
olivedrab:"#6B8E23",orange:"#FFA500",orangered:"#FF4500",orchid:"#DA70D6",palegoldenrod:"#EEE8AA",palegreen:"#98FB98",paleturquoise:"#AFEEEE",palevioletred:"#DB7093",papayawhip:"#FFEFD5",peachpuff:"#FFDAB9",peru:"#CD853F",pink:"#FFC0CB",plum:"#DDA0DD",powderblue:"#B0E0E6",purple:"#800080",red:"#FF0000",rosybrown:"#BC8F8F",royalblue:"#4169E1",saddlebrown:"#8B4513",salmon:"#FA8072",sandybrown:"#F4A460",seagreen:"#2E8B57",seashell:"#FFF5EE",sienna:"#A0522D",silver:"#C0C0C0",skyblue:"#87CEEB",slateblue:"#6A5ACD",
slategray:"#708090",snow:"#FFFAFA",springgreen:"#00FF7F",steelblue:"#4682B4",tan:"#D2B48C",teal:"#008080",thistle:"#D8BFD8",tomato:"#FF6347",turquoise:"#40E0D0",violet:"#EE82EE",wheat:"#F5DEB3",white:"#FFFFFF",whitesmoke:"#F5F5F5",yellow:"#FFFF00",yellowgreen:"#9ACD32"};return{toHex:function(a){var b;if(!(b=JSG.commons.Strings.startsWith(a,"#")?a:c[a.trim().toLowerCase()])){var d=a?a.split(","):[];if(2<d.length){a=-1;b=d[0].trim();a=b.indexOf("(");b=-1<a?b.substring(a+1):b;var e=d[1].trim(),d=d[2].trim();
a=d.indexOf(")");d=-1<a?d.substring(0,a):d;b=JSG.graph.Utils.colorFromRGB(parseFloat(b),parseFloat(e),parseFloat(d))}else b="#FFFFFF"}return b},toRGB:function(a){a=this.toHex(a);a=JSG.Strings.cut(a,"#");a=parseInt(a,16);return"rgb("+(a>>16)+","+(a>>8&255)+","+(a&255)+")"},toRGBA:function(a,b){var d=this.toRGB(a),d=JSG.Strings.cut(d,"rgb"),d=JSG.Strings.cut(d,void 0,")");b=Math.max(0,Math.min(b,1));return"rgba"+d+","+b+")"}}}();JSG.namespace("JSG.SVG");
JSG.SVG.Defs=function(){var c=function(b){var a=JSG.ptCache.get(b.attribute("x1",0),b.attribute("y1",0));b=JSG.ptCache.get(b.attribute("x2",1),b.attribute("y2",0));var d=JSG.geometry.Utils.toDegrees(b.subtract(a).angle());JSG.ptCache.release(a,b);return d},a=function(b){var a=b["stop-color"]||"#FFFFFF";b=(b=b["stop-opacity"])?parseFloat(b):-1;return-1<b&&1>b?JSG.SVG.Color.toRGBA(a,b):JSG.SVG.Color.toHex(a)},b=function(b,d){var e=b.getFormat();e.setFillStyle(JSG.graph.attr.FormatAttributes.FillStyle.GRADIENT);
0<d.length&&e.setFillColor(a(d[0].styles));1<d.length&&e.setGradientColor(a(d[d.length-1].styles))},d={toJSG:function(a,d){if(d&&d instanceof JSG.graph.model.GraphItem){var e=d.getFormat();b(d,this.children);e.setGradientType(JSG.graph.attr.FormatAttributes.GradientStyle.LINEAR);e.setGradientAngle(c(this))}return d},convert:function(){var b=this.getTransformMatrix(),a=b.applyToPoint(JSG.SVG.Unit.toPixels(this.attribute("x1",0),this.attribute("y1",0),this));this.attributes.x1=a.x;this.attributes.y1=
a.y;a=b.applyToPoint(JSG.SVG.Unit.toPixels(this.attribute("x2",0),this.attribute("y2",0),this));this.attributes.x1=a.x;this.attributes.y1=a.y}},e={toJSG:function(a,d){if(d&&d instanceof JSG.graph.model.GraphItem){var e=d.getFormat(),f;f=100*this.attribute("cx",0);var c=100*this.attribute("cy",0);f=JSG.SVG.Unit.toPercentage(f,c,this);b(d,this.children);e.setGradientType(JSG.graph.attr.FormatAttributes.GradientStyle.RADIAL);e.setGradientOffsetX(f.x);e.setGradientOffsetY(f.y)}return d},convert:function(){var b=
this.getTransformMatrix().applyToPoint(JSG.SVG.Unit.toPixels(this.attribute("cx",0),this.attribute("cy",0),this));this.attributes.cx=b.x;this.attributes.cy=b.y}},f={lineargradient:function(b){b=JSG.SVG.Element.fromNode(b);return JSG.SVG.mixin(b,d)},radialgradient:function(b){b=JSG.SVG.Element.fromNode(b);return JSG.SVG.mixin(b,e)}};return{isDefinition:function(b){return!!f[b.name]},createElement:function(b){var a=f[b.nodeName.toLowerCase()];return a?a(b):void 0}}}();JSG.namespace("JSG.SVG");
JSG.SVG.Element=function(c){this.name=c;this.parent=void 0;this.children=[];this.styles={};this.attributes={};this.matrix=void 0};
JSG.SVG.Element.fromNode=function(c){var a=new JSG.SVG.Element(c.nodeName.toLowerCase()),b,d,e=c.attributes,f,h=e?e.length:0;"#text"===a.name&&(a.attributes.text=c.nodeValue);for(f=0;f<h;f++)b=e[f],d=b.nodeName.toLowerCase(),"viewbox"===d?a.attributes[d]=JSG.SVG.ViewBox.createFrom(a,b.value):"style"===d?(b=JSG.SVG.Styles.parse(b.value),a.styles=JSG.SVG.merge(b,a.styles,!0)):JSG.SVG.Styles.isKnown(d)?a.styles[d]=b.value:a.attributes[d]=b.value;a.matrix=JSG.SVG.Transform.getMatrix(a);e=c.childNodes;
f=0;for(h=e.length;f<h;f++)c=e[f],c=(c=(c=JSG.SVG.Shapes.createElement(c))||JSG.SVG.Defs.createElement(e[f]))||JSG.SVG.Element.fromNode(e[f]),a.addChild(c);return a};JSG.SVG.Element.prototype.addChild=function(c){if("#text"!==c.name||"text"===this.name||"tspan"===this.name)this.children.push(c),c.parent=this};JSG.SVG.Element.prototype.firstChild=function(){return 0<this.children.length?this.children[0]:void 0};JSG.SVG.Element.prototype.attribute=function(c,a){return this.attributes[c]||a};
JSG.SVG.Element.prototype.style=function(c,a){return this.styles[c]||a};JSG.SVG.Element.prototype.getTransformMatrix=function(){var c=this.matrix||new JSG.SVG.Matrix,a=this.parent?this.parent.getTransformMatrix():new JSG.SVG.Matrix;return(new JSG.SVG.Matrix).setTo(a).multiply(c)};JSG.SVG.Element.prototype.convert=function(){};JSG.SVG.Element.prototype.convertValues=function(){this.convert();var c,a=this.children,b,d=a.length;for(b=0;b<d;b++)c=a[b],c.convertValues()};
JSG.SVG.Element.prototype.viewbox=function(){return this.attributes.viewbox||(this.parent?this.parent.viewbox():void 0)};JSG.SVG.Element.prototype.viewport=function(){return this.attributes.width&&this.attributes.height?{width:this.attributes.width,height:this.attributes.height}:this.parent?this.parent.viewport():void 0};JSG.SVG.Element.prototype.fontSize=function(){var c=this.style("font-size");return c?JSG.SVG.Unit.toPx(c):this.parent?this.parent.fontSize():void 0};
JSG.SVG.Element.prototype.definition=function(c){var a;this.children.filter(function(b){return"defs"===b.name}).every(function(b){a=b.children.reduce(function(b,a){return b||(a.attributes.id===c?a:void 0)},void 0);return!a});return a||(this.parent?this.parent.definition(c):void 0)};JSG.SVG.Element.prototype.toJSG=function(c){};JSG.namespace("JSG.SVG");
JSG.SVG.Ellipse=function(){var c={toJSG:function(a){var b=new JSG.graph.model.Node(new JSG.graph.model.shapes.EllipseShape);b.evaluate();var d=JSG.ptCache.get(),e=this.getTransformMatrix(),e=JSG.geometry.Utils.toRadians(e.getRotation());d.x=2*a.deviceToLogX(this.attribute("rx",0));d.y=2*a.deviceToLogY(this.attribute("ry",0));b.setSizeToPoint(d);d.x=a.deviceToLogX(this.attribute("cx",0));d.y=a.deviceToLogY(this.attribute("cy",0));b.setPinPointTo(d);b.rotate(e);JSG.ptCache.release(d);JSG.SVG.Styles.apply(this,
b,a);return b},convert:function(){var a=this.getTransformMatrix(),b=a.applyToPoint(JSG.SVG.Unit.toPixels(this.attribute("rx",0),this.attribute("ry",0),this));this.attributes.rx=b.x;this.attributes.ry=b.y;b=a.applyToPoint(JSG.SVG.Unit.toPixels(this.attribute("cx",0),this.attribute("cy",0),this));this.attributes.cx=b.x;this.attributes.cy=b.y}};return{createFrom:function(a){a=JSG.SVG.Element.fromNode(a);return JSG.SVG.mixin(a,c)}}}();JSG.namespace("JSG.SVG");
JSG.SVG.Group=function(){var c={toJSG:function(a){var b=JSG.graph.attr.consts,d=this,e=new JSG.graph.model.Node;e.setItemAttribute(JSG.graph.attr.ItemAttributes.SELECTIONMODE,b.SelectionMode.AREA|b.SelectionMode.SELECTPARENT);e.getFormat().setFillStyle(JSG.graph.attr.FormatAttributes.FillStyle.NONE);e.getFormat().setLineStyle(JSG.graph.attr.FormatAttributes.LineStyle.NONE);e.evaluate();e.setType("group");var f,c=JSG.ptCache.get(),g,m=[];this.children.forEach(function(b){JSG.SVG.merge(d.styles,b.styles);
if(g=b.toJSG(a))g.refresh(),m.push(g),f?f.union(g.getBoundingBox()):f=g.getBoundingBox()});f=f||new JSG.geometry.BoundingBox;f.getTopLeft(c);e.setBoundingBoxTo(f);c.x=this.attributes.x?JSG.SVG.Unit.toPxX(this.attributes.x,this):c.x;c.y=this.attributes.y?JSG.SVG.Unit.toPxY(this.attributes.y,this):c.y;e.setOriginTo(c);var n=e.getAngle().getValue();f.getTopLeft();m.forEach(function(b){var a,d,g;d=b.getItemAttributes();d.setSizeable(!1);d.setMoveable(JSG.graph.attr.consts.Moveable.NONE);b.getOrigin(c);
e.translateFromParent(c);b.rotate(-n);b.setOriginTo(c);a=b.getPin();d=0!==f.getWidth()?a.getX().getValue()/f.getWidth()+" * Parent!WIDTH":void 0;g=0!==f.getHeight()?a.getY().getValue()/f.getHeight()+" * Parent!HEIGHT":void 0;a.setCoordinate(new JSG.graph.expr.NumberExpression(0,d),new JSG.graph.expr.NumberExpression(0,g));a=b.getSize();d=0!==f.getWidth()?a.getWidth().getValue()/f.getWidth()+" * Parent!WIDTH":void 0;g=0!==f.getHeight()?a.getHeight().getValue()/f.getHeight()+" * Parent!HEIGHT":void 0;
b.setSize(new JSG.graph.expr.NumberExpression(0,d),new JSG.graph.expr.NumberExpression(0,g));e.addItem(b)});JSG.ptCache.release(c);return e},convert:function(){}};return{createFrom:function(a){a=JSG.SVG.Element.fromNode(a);return JSG.SVG.mixin(a,c)}}}();JSG.namespace("JSG.SVG");
JSG.SVG.Line=function(){var c={toJSG:function(a){var b=new JSG.graph.model.Edge;b.evaluate();var d=new JSG.geometry.Point;d.x=a.deviceToLogX(this.attribute("x1",0));d.y=a.deviceToLogY(this.attribute("y1",0));var e=new JSG.geometry.Point;e.x=a.deviceToLogX(this.attribute("x2",0));e.y=a.deviceToLogY(this.attribute("y2",0));b.setStartPointTo(d);b.setEndPointTo(e);JSG.SVG.Styles.apply(this,b,a);return b},convert:function(){var a=this.getTransformMatrix(),b=JSG.SVG.Unit.toPixels(this.attribute("x1",0),
this.attribute("y1",0),this);a.applyToPoint(b);this.attributes.x1=b.x;this.attributes.y1=b.y;b=JSG.SVG.Unit.toPixels(this.attribute("x2",0),this.attribute("y2",0),this);a.applyToPoint(b);this.attributes.x2=b.x;this.attributes.y2=b.y}};return{createFrom:function(a){a=JSG.SVG.Element.fromNode(a);return JSG.SVG.mixin(a,c)}}}();JSG.namespace("JSG.SVG");JSG.SVG.Matrix=function(){this.setIdentity()};
JSG.SVG.Matrix.prototype.copy=function(){return(new JSG.SVG.Matrix).set(this.a,this.b,this.c,this.d,this.e,this.f)};JSG.SVG.Matrix.prototype.set=function(c,a,b,d,e,f){this.a=c;this.b=a;this.c=b;this.d=d;this.e=e;this.f=f;return this};JSG.SVG.Matrix.prototype.setTo=function(c){return this.set(c.a,c.b,c.c,c.d,c.e,c.f)};JSG.SVG.Matrix.prototype.setIdentity=function(){return this.set(1,0,0,1,0,0)};
JSG.SVG.Matrix.prototype.multiply=function(c){return this.set(this.a*c.a+this.c*c.b,this.b*c.a+this.d*c.b,this.a*c.c+this.c*c.d,this.b*c.c+this.d*c.d,this.a*c.e+this.c*c.f+this.e,this.b*c.e+this.d*c.f+this.f)};JSG.SVG.Matrix.prototype.applyToPoint=function(c){var a=this.b*c.x+this.d*c.y+this.f;c.x=this.a*c.x+this.c*c.y+this.e;c.y=a;return c};
JSG.SVG.Matrix.prototype.rotate=function(c){var a=c?JSG.geometry.Utils.toRadians(c):0;c=Math.cos(a);var a=Math.sin(a),b=new JSG.SVG.Matrix;b.a=c;b.b=a;b.c=-a;b.d=c;return this.multiply(b)};JSG.SVG.Matrix.prototype.rotatePoint=function(c,a){return{x:this.a*c+this.c*a,y:this.b*c+this.d*a}};JSG.SVG.Matrix.prototype.getRotation=function(){var c=this.rotatePoint(1,0);return JSG.geometry.Utils.toDegrees(Math.atan2(c.y,c.x))};
JSG.SVG.Matrix.prototype.scale=function(c,a){var b=new JSG.SVG.Matrix;b.a=c||1;b.d=a||b.a;return this.multiply(b)};JSG.SVG.Matrix.prototype.getScale=function(){return{x:Math.sqrt(this.a*this.a+this.b*this.b),y:Math.sqrt(this.c*this.c+this.d*this.d)}};JSG.SVG.Matrix.prototype.translate=function(c,a){var b=new JSG.SVG.Matrix;b.e=c||0;b.f=a||0;return this.multiply(b)};JSG.SVG.Matrix.prototype.getTranslation=function(){return{x:this.e,y:this.f}};
JSG.SVG.Matrix.prototype.toString=function(){return"["+this.a+", "+this.b+", "+this.c+", "+this.d+", "+this.e+", "+this.f+"]"};JSG.namespace("JSG.SVG");
JSG.SVG.Path=function(){var c={toJSG:function(a){this.attribute("d","").trim();var b=new JSG.graph.model.shapes.PathShape,d=new JSG.graph.model.Node(b);d.evaluate();d.disableEvents();d.disableRefresh();d.getShape().disableRefresh();var e,f=this.attribute("data",[]),c,g=f.length;for(c=0;c<g;c++)e=f[c],e.x=a.deviceToLogX(e.x),e.y=a.deviceToLogY(e.y),b.addCoordinate(JSG.graph.Coordinate.fromPoint(e),e.cmd),e.closed&&b.addClose();d.getShape().enableRefresh();d.enableRefresh(!0);d.enableEvents();JSG.SVG.Utils.translateCoords(d);
JSG.SVG.Styles.setDefault(this,"stroke-width","1");JSG.SVG.Styles.setDefault(this,"fill","#000000");JSG.SVG.Styles.apply(this,d,a);return d},convert:function(){var a=this.getTransformMatrix(),b,d=JSG.SVG.PathData.createPoints(this),e,f=d.length;for(e=0;e<f;e++)b=d[e],a.applyToPoint(b);this.attributes.data=d}};return{createFrom:function(a){a=JSG.SVG.Element.fromNode(a);return JSG.SVG.mixin(a,c)}}}();JSG.namespace("JSG.SVG");
JSG.SVG.PathData=function(){var c,a,b=function(){var b=JSG.graph.model.shapes.PathShape.isValidCmd;return function(a){return a&&b(a.toUpperCase())}}(),d=function(){var b=/[a-z]/;return function(a){return b.test(a)}}(),e=function(b){for(var d=b.charAt(c);c<a&&("\t"===d||" "===d);)d=b.charAt(++c)},f=function(d){var f,h="";e(d);f=d.charAt(c);b(f)&&(c++,h+=f,e(d),f=d.charAt(c));for(;c<=a&&(0===h.length||","!==f&&"\t"!==f&&" "!==f&&!b(f));)h+=f,f=d.charAt(++c);return h},h={x:"",y:"",reset:function(){this.y=
this.x=""}};return{createPoints:function(g){var m=[],n=g.attribute("d","").trim();a=n.length;if(0<a){var k,s=!1,p=JSG.ptCache.get(),q=JSG.ptCache.get(0,0),r=JSG.ptCache.get(0,0);for(c=0;c<a;){h.x=f(n);h.y=f(n);k=h;var l=k.x.charAt(0);if(l=b(l)?l:void 0)k.x=k.x.substring(1);k=l;var l=h,t=g,u=p;l.x&&l.y?(u.x=JSG.SVG.Unit.toPxX(l.x.trim(),t),u.y=JSG.SVG.Unit.toPxY(l.y.trim(),t),l=!0):l=!1;l&&((s=k?d(k):s)?p.add(k?q:r):r.setTo(p),q.setTo(p),k=k?k.toUpperCase():k,l=p.copy(),l.cmd=k,m.push(l));k=n;e(k);
c=(k=(k=k.charAt(c))&&"Z"===k.toUpperCase())?c+1:c;k&&(m[m.length-1].closed=!0);h.reset()}JSG.ptCache.release(p,r,q)}return m}}}();JSG.namespace("JSG.SVG");
JSG.SVG.Polygon=function(){var c={isClosed:!0,toCoordinates:function(a,b){var d=[],e,f=a.length;for(e=0;e<f;e++){var c=a[e];d.push(JSG.graph.Coordinate.fromXY(b.deviceToLogX(c.x),b.deviceToLogY(c.y)))}return d},toJSG:function(a){var b=new JSG.graph.model.Node(new JSG.graph.model.shapes.PolygonShape);b.setItemAttribute(JSG.graph.attr.ItemAttributes.CLOSED,this.isClosed);b.evaluate();var d=this.attribute("points",[]);b.getShape().setCoordinates(this.toCoordinates(d,a));JSG.SVG.Utils.translateCoords(b);
JSG.SVG.Styles.apply(this,b,a);return b},convert:function(){var a=this.getTransformMatrix(),b=[],d,e=this.attribute("points","").split(" "),f,c=e.length;for(f=0;f<c;f++)d=e[f].trim().split(","),1<d.length&&(d=a.applyToPoint(JSG.SVG.Unit.toPixels(d[0],d[1],this)),b.push(d));this.attributes.points=b}};return{createFrom:function(a){a=JSG.SVG.Element.fromNode(a);return JSG.SVG.mixin(a,c)}}}();JSG.namespace("JSG.SVG");
JSG.SVG.Rect=function(){var c={toJSG:function(a){var b=this.attributes.rx&&this.attributes.ry?JSG.graphItemFactory.createItemFromString("roundRect"):new JSG.graph.model.Node;b.evaluate();var d=JSG.ptCache.get(),e=this.getTransformMatrix(),e=JSG.geometry.Utils.toRadians(e.getRotation());d.x=a.deviceToLogX(this.attribute("width",0));d.y=a.deviceToLogX(this.attribute("height",0));b.setSizeToPoint(d);d.x=a.deviceToLogX(this.attribute("x",0));d.y=a.deviceToLogY(this.attribute("y",0));b.setOriginTo(d);
b.rotate(e);JSG.ptCache.release(d);JSG.SVG.Styles.apply(this,b,a);return b},convert:function(){var a=this.getTransformMatrix(),b=a.applyToPoint(JSG.SVG.Unit.toPixels(this.attribute("x",0),this.attribute("y",0),this));this.attributes.x=b.x;this.attributes.y=b.y;a=a.getScale();this.attributes.width=JSG.SVG.Unit.toPxX(this.attribute("width",0),this)*a.x;this.attributes.height=JSG.SVG.Unit.toPxY(this.attribute("height",0),this)*a.y}};return{createFrom:function(a){a=JSG.SVG.Element.fromNode(a);return JSG.SVG.mixin(a,
c)}}}();JSG.namespace("JSG.SVG");
JSG.SVG.Shapes=function(){var c={circle:function(a){return JSG.SVG.Circle.createFrom(a)},ellipse:function(a){return JSG.SVG.Ellipse.createFrom(a)},g:function(a){return JSG.SVG.Group.createFrom(a)},line:function(a){return JSG.SVG.Line.createFrom(a)},path:function(a){return JSG.SVG.Path.createFrom(a)},polygon:function(a){return JSG.SVG.Polygon.createFrom(a)},polyline:function(a){a=JSG.SVG.Polygon.createFrom(a);a.isClosed=!1;return a},rect:function(a){return JSG.SVG.Rect.createFrom(a)},svg:function(a){return JSG.SVG.Svg.createFrom(a)},
text:function(a){return JSG.SVG.Text.createFrom(a)}};return{isShape:function(a){return!!c[a.name]},createElement:function(a){var b=c[a.nodeName.toLowerCase()];return b?b(a):void 0}}}();JSG.namespace("JSG.SVG");
JSG.SVG.Styles=function(){var c={fill:function(b,a,e,f){JSG.Strings.startsWith(b,"url(#")?(b=JSG.Strings.cut(b,"url(#",")"),(a=a.definition(b))&&a.toJSG(f,e)):"none"===b.toLowerCase()?e.getFormat().setFillStyle(JSG.graph.attr.FormatAttributes.FillStyle.NONE):(f=JSG.SVG.Color.toHex(b),e instanceof JSG.graph.model.TextNode?e.getTextFormat().setFontColor(f):e.getFormat().setFillColor(f))},opacity:function(b,a,e,f){a=e.getFormat();e=e.getTextFormat();b=parseFloat(b);a.setTransparency(100*b);a.setLineColor(this.applyAlpha(a.getLineColor().getValue(),
b));e.setFontColor(this.applyAlpha(e.getFontColor().getValue(),b))},applyAlpha:function(b,a){return JSG.graph.Utils.applyAlphaToColor(b,a)},stroke:function(b,a,e,f){"none"===b.toLowerCase()?e.getFormat().setLineStyle(JSG.graph.attr.FormatAttributes.LineStyle.NONE):(b=JSG.SVG.Color.toHex(b),e.getFormat().setLineColor(b))},"stroke-dasharray":function(b,a,e,f){a=JSG.graph.attr.FormatAttributes.LineStyle;e=e.getFormat();b=b.split(",");f=a.DOT;var c,g,m=b.length-1;for(g=0;g<m;g++)if(c=b[g].trim(),c!==
b[g+1].trim()){if(f=f===a.DASHDOT?a.DASHDOTDOT:a.DASHDOT,f===a.DASHDOTDOT)break}else f===a.DOT&&5<parseInt(c,10)&&(f=a.DASH);e.setLineStyle(f)},"stroke-linecap":function(b,a,e,f){a=JSG.graph.attr.FormatAttributes.LineCap;f=a.BUTT;switch(b.toLowerCase()){case "round":f=a.ROUND;break;case "square":f=a.SQUARE}e.getFormat().setLineCap(f)},"stroke-width":function(b,a,e,f){b=JSG.SVG.Unit.toPx(b,a);a=a.getTransformMatrix().getScale();b=f.deviceToLogX(b*a.x);e.getFormat().setLineWidth(b)},"font-family":function(b,
a,e,f){e.getTextFormat().setFontName(b)},"font-style":function(b,a,e,f){a=JSG.graph.attr.TextFormatAttributes;f=a.FontStyle.NORMAL;switch(b.toLowerCase()){case "bold":f|=a.FontStyle.BOLD;break;case "italic":f|=a.FontStyle.ITALIC;break;case "underline":f|=a.FontStyle.UNDERLINE}e.getTextFormat().setFontStyle(f)},"font-weight":function(b,a,e,f){a=JSG.graph.attr.TextFormatAttributes;b="bold"===b.toLowerCase()?a.FontStyle.BOLD:a.FontStyle.NORMAL;e.getTextFormat().setFontStyle(b)},"font-size":function(b,
a,e,f){b=JSG.SVG.Unit.toPt(b,a);a=a.getTransformMatrix().getScale();e.getTextFormat().setFontSize(b*a.y)},"text-anchor":function(b,a,e,f){a=JSG.graph.attr.TextFormatAttributes;f=a.TextAlignment.LEFT;switch(b.toLowerCase()){case "midel":f=a.TextAlignment.CENTER;break;case "end":f=a.TextAlignment.RIGHT}e.getTextFormat().setHorizontalAlignment(f)},"text-decoration":function(b,a,e,f){"underline"===b.toLowerCase()&&(b=e.getTextFormat().getFontStyle().getValue(),b|=JSG.graph.attr.TextFormatAttributes.FontStyle.UNDERLINE,
e.getTextFormat().setFontStyle(b))}},a=function(b,d){var e=d?d.styles[b]:void 0;return e&&"inherit"===e.toLowerCase()?a(b,d.parent):e};return{apply:function(b,d,e){var f=b.styles,h,g=!1;d.getFormat().setLineWidth(JSG.graph.attr.FormatAttributes.LineStyle.NONE);for(h in f)if(f.hasOwnProperty(h)&&c[h])if("opacity"===h)g=!0;else c[h](a(h,b),b,d,e);g&&c.opacity(f.opacity,b,d,e)},setDefault:function(b,a,e){this.isKnown(a)&&!b.styles[a]&&(b.styles[a]=e)},parse:function(b){var a={},e=b.split(";"),f,c=e.length;
for(f=0;f<c;f++)b=e[f].trim().split(":"),a[b[0].trim().toLowerCase()]=2===b.length?b[1].trim():"";return a},isKnown:function(b){return b&&!!c[b]}}}();JSG.namespace("JSG.SVG");
JSG.SVG.Svg=function(){var c={toJSG:function(a){var b=new JSG.graph.model.Node;b.evaluate();var d=JSG.ptCache.get(),c=this.getTransformMatrix(),c=JSG.geometry.Utils.toRadians(c.getRotation());d.x=a.deviceToLogX(this.attribute("width",0));d.y=a.deviceToLogX(this.attribute("height",0));b.setSizeToPoint(d);d.x=a.deviceToLogX(this.attribute("x",0));d.y=a.deviceToLogY(this.attribute("y",0));b.setOriginTo(d);b.rotate(c);JSG.ptCache.release(d);JSG.SVG.Styles.apply(this,b,a);var c=this.children,f,h=c.length;
for(f=0;f<h;f++)(d=c[f].toJSG(a))&&b.addItem(d);return b},convert:function(){var a=this.getTransformMatrix(),b=a.applyToPoint(JSG.SVG.Unit.toPixels(this.attribute("x",0),this.attribute("y",0),this));this.attributes.x=b.x;this.attributes.y=b.y;this.attributes.width=JSG.SVG.Unit.toPxX(this.attribute("width",0),this);this.attributes.height=JSG.SVG.Unit.toPxY(this.attribute("height",0),this);a=a.getScale();this.attributes.viewbox&&(b=this.attributes.viewbox.getScale(this.attributes.width,this.attributes.height),
a.x*=1/b.width,a.y*=1/b.height);this.attributes.width*=a.x;this.attributes.height*=a.y}};return{createFrom:function(a){a=JSG.SVG.Element.fromNode(a);return JSG.SVG.mixin(a,c)}}}();JSG.namespace("JSG.SVG");
JSG.SVG.Text=function(){var c={toJSG:function(a){var b,d=this.children,c,f=d.length,h="",g=new JSG.graph.model.TextNode;for(c=0;c<f;c++)b=d[c],"#text"===b.name?h+=b.attribute("text",""):"tspan"===b.name&&(b=JSG.SVG.TSpan.textFrom(b))&&(h+=b);g.getTextFormat().setVerticalPosition(JSG.graph.attr.TextFormatAttributes.VerticalTextPosition.CUSTOM);g.getTextFormat().setHorizontalPosition(JSG.graph.attr.TextFormatAttributes.HorizontalTextPosition.CUSTOM);JSG.SVG.Styles.apply(this,g,a);g.setText(h);g.evaluate();
d=JSG.ptCache.get();c=this.getTransformMatrix();c=JSG.geometry.Utils.toRadians(c.getRotation());d.x=a.deviceToLogX(this.attribute("x",0));d.y=a.deviceToLogY(this.attribute("y",0));g.setPinPointTo(d);g.rotate(c);JSG.ptCache.release(d);return g},convert:function(){var a=this.getTransformMatrix().applyToPoint(JSG.SVG.Unit.toPixels(this.attribute("x",0),this.attribute("y",0),this));this.attributes.x=a.x;this.attributes.y=a.y}};return{createFrom:function(a){a=JSG.SVG.Element.fromNode(a);return JSG.SVG.mixin(a,
c)}}}();JSG.namespace("JSG.SVG");
JSG.SVG.Transform=function(){var c={matrix:function(b,a){return b.set(parseFloat(a[0]),parseFloat(a[1]),parseFloat(a[2]),parseFloat(a[3]),parseFloat(a[4]),parseFloat(a[5]))},translate:function(b,a){return b.translate(parseFloat(a[0]),parseFloat(a[1]))},scale:function(a,c){var e=0<c.length?parseFloat(c[0]):1,f=1<c.length?parseFloat(c[1]):e;return a.scale(e,f)},rotate:function(a,c){var e=0<c.length?-parseInt(c[0],10):0;return a.rotate(e)}},a=function(a){var c=a.substring(0,a.indexOf("("));a=JSG.Strings.cut(a,
"(",")");a=a.match(/[a-zA-Z0-9.]+/g)||[];return{transform:c,params:a}};return{getMatrix:function(b){var d=b.attributes.transform,e;if(d){e=new JSG.SVG.Matrix;var f=[];if(d){var d=d.match(/[a-zA-Z]+\(([^)]+)\)/g),h,g=d.length;for(h=0;h<g;h++)f.push(a(d[h]))}g=f.length;if(0<g)for(h=0;h<g;h++)(d=c[f[h].transform])&&d(e,f[h].params)}else e=new JSG.SVG.Matrix;b.attributes.viewbox&&(f=b.attributes.viewbox,d=JSG.SVG.Unit.toPxX(b.attribute("width",f.width),b),b=JSG.SVG.Unit.toPxY(b.attribute("height",f.height),
b),e.scale(d/f.width,b/f.height),e.translate(f.minX,f.minY));return e}}}();JSG.namespace("JSG.SVG");
JSG.SVG.TSpan=function(){var c={fill:function(a,b){return"color:"+JSG.SVG.Color.toHex(a)+";"},"font-weight":function(a,b){return"font-weight:"+a+";"},"font-size":function(a,b){return"font-size:"+JSG.SVG.Unit.toPt(a,b)+"pt;"},"font-family":function(a,b){return"font-family:"+a+";"},"font-style":function(a,b){return"font-style:"+a+";"}};return{textFrom:function(a){var b=a.firstChild();if(b){var b=b.attribute("text",""),d,e=a.styles,f="";for(d in e)e.hasOwnProperty(d)&&c[d]&&(f+=c[d](e[d],b,a));b="\x3cspan"+
('style\x3d"'+f+'"'?" "+('style\x3d"'+f+'"'):"")+"\x3e"+b+"\x3c/span\x3e"}return b}}}();JSG.namespace("JSG.SVG");
JSG.SVG.Unit=function(){var c=0,a="px",b=function(a){if(a)return a.viewbox()||a.viewport()},d={em:function(a,b,c){b=b?b.fontSize():void 0;return a*(b||12)},ex:function(a,b,c){return this.em(a,b,c)},cm:function(a,b,c){return this["in"](a,c)/2.54},mm:function(a,b,c){return this.cm(a,c)/10},"in":function(a,b,c){b=JSG.dpi;return a*(c?b.x:b.y)},pc:function(a,b,c){return 12*this.pt(a,c)},pt:function(a,b,c){return this["in"](a,c)/72},"%":function(a,c,d){c=(c=b(c))?d?c.width:c.height:1;return c*a/100}},e=
function(b,e,g){b=b.toString();c=parseFloat(b);a=JSG.Strings.cut(b,c.toString());return(b=d[a])?b.call(d,c,e,g):c};return{toPt:function(a,b){return 0.75*this.toPxX(a,b)},toPx:function(a,b){return this.toPxX(a,b)},toPxX:function(a,b){return e(a,b,!0)},toPxY:function(a,b){return e(a,b,!1)},toPixels:function(a,b,c){return{x:e(a,c,!0),y:e(b,c,!1)}},toPercentage:function(a,c,d){c=c||0===c?c:a;d=b(d);return{x:d?a/d.width:0,y:d?c/d.height:0}}}}();JSG.namespace("JSG.SVG");
JSG.SVG.Utils=function(){return{translateCoords:function(c){var a=c.getShape().getPointList().getBoundingBox(),b=a.getSize(),d=a.getTopLeft(),e=JSG.geometry.Utils,f=JSG.ptCache.get();c.getShape().getCoordinates().forEach(function(a){a.toPoint(f);f.translate(-d.x,-d.y);var c=0!==b.x?f.x/b.x:0,m=0!==b.y?f.y/b.y:0;a.getX().setFormula("width * "+e.roundTo(c,2));a.getY().setFormula("height * "+e.roundTo(m,2))});a=c.getPin();a.getLocalX().setFormula("WIDTH * 0.5");a.getLocalY().setFormula("HEIGHT * 0.5");
c.setSize(b.x,b.y);c.setOriginTo(d);JSG.ptCache.release(f)}}}();JSG.namespace("JSG.SVG");JSG.SVG.ViewBox=function(){var c=function(a){if(a)return a=a.split(/[,\s]+/),{minX:JSG.SVG.Unit.toPxX(a[0])||0,minY:JSG.SVG.Unit.toPxY(a[1])||0,width:JSG.SVG.Unit.toPxX(a[2])||0,height:JSG.SVG.Unit.toPxY(a[3])||0,getScale:function(a,c){c=c||0===c?c:a;return{width:a?a/this.width:1,height:c?c/this.height:1}}}};return{createFrom:function(a,b){return c(b)}}}();